# Generated by Django 3.1.5 on 2021-02-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerotoninRush', '0005_meal_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
    ]
