# Generated by Django 3.1.5 on 2021-03-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerotoninRush', '0007_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.CharField(max_length=250),
        ),
    ]
